name: Sync Worker File

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00自动同步

jobs:
  file-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予工作流提交权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create directory
      run: mkdir -p src  # 自动创建src目录（如果不存在）

    - name: Download worker file
      run: |
        curl -fsSL "https://raw.githubusercontent.com/ZhiXuanWang/cf-speed-dns/main/index.html" -o index.html

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "chore: Auto-update index.html" || echo "No changes to commit"
        git push
