name: Sync Worker File

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 6 小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  file-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予工作流提交权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create directory
      run: mkdir -p src  # 自动创建src目录（如果不存在）

    - name: Download worker file
      run: |
        curl -fsSL "https://raw.githubusercontent.com/ppttgov/cf-speed-dns/refs/heads/main/index.html" -o index.html

    - name: Detect changes
      id: changes
      run: |
        git status -s | grep -E 'index\.html' && echo "changes_detected=true" >> $GITHUB_OUTPUT || echo "No file changes"

    - name: Commit and push
      if: steps.changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "chore: Auto-sync files at $(date +'%Y-%m-%d %H:%M UTC')"
        git push
